### PR TITLE
Update to GeometryBasics.jl

### PR DESCRIPTION
**Pull request by PavanChaggar**
This PR just updates the package to use GeometryBasics.jl instead of the older GeometryTypes.jl. I've locally tested the computability with GLMakie and surface meshes seem to plot nicely!

### CODE REVIEW

**Comment by Tokazama** [comment]
Do we want to remove the manifts.toml file?

**Comment by PavanChaggar** [comment]
oops. I've removed the Manifest.toml and added it to the .gitignore.

**Comment by Tokazama** [comment]
This is awesome! Did you want to work on tests to make sure this is up and running or do this piecewise? Just let me know what you need from me.

**Comment by PavanChaggar** [comment]
I havent changed anything with the tests. It was only a small update so didn't get familiar enough with the code to write tests, I had just been seeing if GIFTI files loaded and worked with Makie, but I don know if it makes sense to keep a gift file in the repo just for testing. Anyway, happy to have this one merged and then deal with tests later.

**Pull request merged**
